export { default as contacts } from "./dashBoardComponents/contacts/contacts"
export {default as lastActivity} from "./dashBoardComponents/lastActivityContacts/lastActivity"
export {default as navLeft} from "./dashBoardComponents/navLeft/navLeft"
export {default as NavUp} from "./dashBoardComponents/NavBarAbove/navBarUp"
export {default as Banner} from "./dashBoardComponents/Banner/banner"
export {default as CardUser} from "./dashBoardComponents/designerCards/Card"
export {default as CategoriesMain} from "./dashBoardComponents/mainCategories/categoriesMain"
export {default as ProjectCard} from "./dashBoardComponents/ProjectCard/ProjectCard"
export {default as Footer} from "./dashBoardComponents/footer/footer"
export {default as RectangleInformation} from "./LogInComponents/RectangleInformation/RectangleInformation"
export {default as InputText} from "./LogInComponents/InputText/InputText"
export {default as ButtonsLogin} from "./LogInComponents/Buttons/Buttons"
export {default as DecorationBackground} from "./LogInComponents/DecorationBackground/DecorationBackground"
export {default as Inputs} from "./SignUpComponents/Inputs/Inputs"
export {default as Button} from "./SignUpComponents/Button/Button"
export {default as TarjetUser} from "./PerfilUserComponents/TarjetUser/TarjetUser"